### ISSUE TITLE
Selecting the tracking ID

### ISSUE THREAD

**Issue by jesserosenfield** [swup/ga-plugin#9]
```
window.ga("set","title",n)
```

Was returning an undefined javascript error.

If you're initializing Google Analytics with google tag manager, this might work for you– it solved the problem for me:

```
var trackingID = window.ga.getAll()[0].get('name');
window.ga(trackingID + ".set","title",n);
```

**Comment by gmrchk** [comment]
Thanks for the tip. 👍 If anyone encounters GA problems, there is also [Gtag plugin](https://github.com/joshuaHallee/swup-gtag-plugin) that should help. It probably depends mainly on how the GA is loaded in the first place, but it's good there are multiple options.
